name: Build Windows 3.10

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: get-cmake
      uses: lukka/get-cmake@v3.21.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build
      run: build
