name: Linux Py 3.9

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get-cmake
      uses: lukka/get-cmake@v3.21.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh
